---
- become: 'yes'
  become_method: sudo
  become_user: root
  hosts: lan
  tasks:
    - apt:
        name: vim
    - community.general.alternatives:
        name: editor
        path: /usr/bin/vim.basic